Document: teapot
Title: Debian teapot Manual
Author: <insert document author here>
Abstract: This manual describes what teapot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/teapot/teapot.sgml.gz

Format: postscript
Files: /usr/share/doc/teapot/teapot.ps.gz

Format: text
Files: /usr/share/doc/teapot/teapot.text.gz

Format: HTML
Index: /usr/share/doc/teapot/html/index.html
Files: /usr/share/doc/teapot/html/*.html
